apiVersion: "rbac.authorization.k8s.io/v1beta1"
kind: RoleBinding
metadata:
  name: {{ template "adoptdog.fullname" . }}
  labels:
    app: {{ template "adoptdog.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
subjects:
- kind: ServiceAccount
  name: {{ template "adoptdog.fullname" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name:  {{ template "adoptdog.fullname" . }}